import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import { getAllCitySlugs } from '../src/data/texasCities.js';
import { blogPosts } from '../src/data/blogPosts.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from .env file (handled by node -r dotenv/config)
dotenv.config();

const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('Error: Supabase environment variables (VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY) are not set.');
  console.error('Make sure your .env file contains these variables.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Slug generators aligned with src/lib/slugify.ts
const generateNameSlug = (companyName: string | null, name: string): string => {
  const displayName = companyName || name;
  return (displayName || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
};

const generateCitySlug = (city: string): string => {
  return (city || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
};

async function generateSitemap() {
  const baseUrl = 'https://solarinstallerstx.com';
  const today = new Date().toISOString().split('T')[0];

  // Attempt to load the id->path map generated by generate-installer-routes
  let idToPath: Record<string, string> | null = null;
  try {
    const mapPath = path.join(process.cwd(), 'src', 'assets', 'installer-paths.json');
    if (fs.existsSync(mapPath)) {
      idToPath = JSON.parse(fs.readFileSync(mapPath, 'utf-8')) as Record<string, string>;
    }
  } catch (e) {
    console.warn('⚠️ Could not load installer-paths.json; falling back to simple slugs');
  }

  // Static pages
  const staticPages = [
    { url: '/', changefreq: 'daily', priority: '1.0' },
    { url: '/about', changefreq: 'monthly', priority: '0.8' },
    { url: '/contact', changefreq: 'monthly', priority: '0.8' },
    { url: '/faq', changefreq: 'monthly', priority: '0.9' },
    { url: '/privacy', changefreq: 'yearly', priority: '0.5' },
    { url: '/terms', changefreq: 'yearly', priority: '0.5' },
    { url: '/refund', changefreq: 'yearly', priority: '0.5' },
    { url: '/affiliate-disclosure', changefreq: 'yearly', priority: '0.5' },

    // Main sections
    { url: '/installers', changefreq: 'daily', priority: '1.0' },
    { url: '/best-solar-companies-texas', changefreq: 'monthly', priority: '1.0' },
    { url: '/quote', changefreq: 'monthly', priority: '0.9' },

    // Learn hub
    { url: '/learn', changefreq: 'monthly', priority: '1.0' },
    { url: '/learn/solar-buying-guide-texas', changefreq: 'monthly', priority: '1.0' },
    { url: '/learn/texas-incentives', changefreq: 'monthly', priority: '1.0' },
    { url: '/learn/choosing-installer', changefreq: 'monthly', priority: '0.9' },
    { url: '/learn/solar-panel-types', changefreq: 'monthly', priority: '0.9' },
    { url: '/learn/battery-storage', changefreq: 'monthly', priority: '0.9' },
    { url: '/learn/solar-financing', changefreq: 'monthly', priority: '0.9' },

    // Trust & Safety
    { url: '/safety-score-explained', changefreq: 'monthly', priority: '0.9' },
    { url: '/how-we-protect-you', changefreq: 'monthly', priority: '0.9' },
    { url: '/sunnova-help', changefreq: 'monthly', priority: '0.8' },

    // Legacy pages - keep for SEO
    { url: '/premium', changefreq: 'monthly', priority: '0.9' },
    { url: '/texas-guide', changefreq: 'monthly', priority: '0.9' },
    { url: '/texas-solar-incentives-2025', changefreq: 'yearly', priority: '1.0' },
  ];

  // Blog pages
  const blogPages = [
    { url: '/blog', changefreq: 'weekly', priority: '1.0' },
    ...blogPosts.map(post => ({
      url: `/blog/${post.slug}`,
      changefreq: 'monthly',
      priority: post.featured ? '1.0' : '0.9'
    })),
  ];

  // City-specific landing pages - Dynamically generated from texasCities data (50+ cities)
  const citySlugs = getAllCitySlugs();
  const cityPages = [
    ...citySlugs.map(slug => ({
      url: `/cities/${slug}`,
      changefreq: 'monthly',
      priority: '0.9'
    })),
    { url: '/nabcep-certified-installers', changefreq: 'monthly', priority: '0.9' },
    { url: '/texas-solar-incentives', changefreq: 'monthly', priority: '0.9' },
  ];

  console.log(`✓ Generated ${citySlugs.length} city pages for sitemap`);

  // Fetch all installers (optional - will continue without if database unavailable)
  let installers: any[] = [];
  try {
    const { data, error } = await supabase
      .from('installers')
      .select('id, name, company_name, location_city, location_state, updated_at')
      .order('name');

    if (error) {
      console.warn('⚠️ Could not fetch installers from database:', error.message);
      console.warn('⚠️ Continuing with sitemap generation (static pages + city pages only)');
    } else {
      installers = data || [];
      console.log(`✓ Loaded ${installers.length} installers from database`);
    }
  } catch (e: any) {
    console.warn('⚠️ Database connection failed:', e.message);
    console.warn('⚠️ Continuing with sitemap generation (static pages + city pages only)');
  }

  // Generate XML
  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n';

  // Add static pages
  staticPages.forEach(page => {
    xml += '  <url>\n';
    xml += `    <loc>${baseUrl}${page.url}</loc>\n`;
    xml += `    <lastmod>${today}</lastmod>\n`;
    xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
    xml += `    <priority>${page.priority}</priority>\n`;
    xml += '  </url>\n';
  });

  // Add city pages
  cityPages.forEach(page => {
    xml += '  <url>\n';
    xml += `    <loc>${baseUrl}${page.url}</loc>\n`;
    xml += `    <lastmod>${today}</lastmod>\n`;
    xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
    xml += `    <priority>${page.priority}</priority>\n`;
    xml += '  </url>\n';
  });

  // Add blog pages
  blogPages.forEach(page => {
    xml += '  <url>\n';
    xml += `    <loc>${baseUrl}${page.url}</loc>\n`;
    xml += `    <lastmod>${today}</lastmod>\n`;
    xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
    xml += `    <priority>${page.priority}</priority>\n`;
    xml += '  </url>\n';
  });

  // Add installer pages using the id->path map when available; otherwise, deduplicate
// CRITICAL FIX: Add installer pages ONLY IF they are canonical URLs  // Use the id->path map to ensure canonical URLs only  // Skip duplicate URLs and any non-canonical variations
  const seenUrls = new Set<string>();
  let duplicatesSkipped = 0;

  installers?.forEach(installer => {
    let urlPath: string;
    if (idToPath && idToPath[installer.id]) {
      urlPath = idToPath[installer.id];
    } else {
      const nameSlug = generateNameSlug(installer.company_name, installer.name);
      const citySlug = generateCitySlug(installer.location_city);
      urlPath = `/installers/${citySlug}/${nameSlug}`;
    }

    // Skip if we've already seen this slug (shouldn't happen with idToPath, but safe)
    if (seenUrls.has(urlPath)) {
      console.warn(`⚠️  Skipping duplicate URL: ${urlPath}`);
      duplicatesSkipped++;
      return;
    }
    seenUrls.add(urlPath);

    const lastmod = installer.updated_at
      ? new Date(installer.updated_at).toISOString().split('T')[0]
      : today;

    xml += '  <url>\n';
    xml += `    <loc>${baseUrl}${urlPath}</loc>\n`;
    xml += `    <lastmod>${lastmod}</lastmod>\n`;
    xml += `    <changefreq>weekly</changefreq>\n`;
    xml += `    <priority>0.8</priority>\n`;
    xml += '  </url>\n';
  });

  xml += '</urlset>';

  // Write to public/sitemap.xml
  const sitemapPath = path.join(process.cwd(), 'public', 'sitemap.xml');
  fs.writeFileSync(sitemapPath, xml, 'utf-8');

  console.log(`✅ Sitemap generated successfully!`);
  console.log(`📄 Total URLs: ${staticPages.length + cityPages.length + blogPages.length + seenUrls.size}`);
  console.log(`   - Static pages: ${staticPages.length}`);
  console.log(`   - City pages: ${cityPages.length}`);
  console.log(`   - Blog pages: ${blogPages.length} (including ${blogPosts.length} posts)`);
  console.log(`   - Installer pages: ${seenUrls.size}`);
  if (duplicatesSkipped > 0) {
    console.log(`   - Duplicates skipped: ${duplicatesSkipped}`);
  }
  console.log(`📍 Location: ${sitemapPath}`);
}

generateSitemap().catch(console.error);